#!/bin/bash

#
# apply dotfiles to your home
#

_REPOS="https://github.com/unagi/dotfiles.git"
_BACKUPDIR=".backup_dotfiles"

cmd_chk() {
    which $1 > /dev/null
    [ $? -ne 0 ] && echo "Please install \"$1\" before execute." >&2 && exit 1
}

case "${OSTYPE}" in
    freebsd*|darwin*)
        echo "setup for MacOSX"
        cmd_chk brew
        brew install autojump coreutils colordiff colorsvn nmap wget
        ;;
    linux*)
        if [ `lsb_release --short --id` == "Ubuntu" ]; then
            echo "setup for Ubuntu"
            sudo apt-get install -y autojump colordiff curl
        fi
        ;;
    *)
        echo "who"
        ;;
esac

cmd_chk git
cmd_chk vim

cd ~
if [ ! -d ~/dotfiles ]; then
    git clone ${_REPOS}
    mkdir -p ~/.vim/bundle
    git clone git://github.com/Shougo/neobundle.vim ~/.vim/bundle/neobundle.vim
fi
cd dotfiles
git submodule update --init --recursive
cd ~

if [ -d ${_BACKUPDIR} ]; then
    rm -rf ${_BACKUPDIR}
fi

mkdir -p ${_BACKUPDIR}
for l in `find dotfiles -mindepth 1 -maxdepth 1 ! -name '.git*' -a ! -name 'README' -a ! -name 'apply_dotfiles'`; do
    [ -a `basename $l` ] && mv `basename $l` ${_BACKUPDIR}/
    ln -s $l `basename $l`
done

echo "Launch vim, run :NeoBundleInstall"

exit 0
