#!/usr/bin/env zsh

#
# apply dotfiles to your home
#

_REPOS="git@github.com:unagi/dotfiles.git"
_BACKUPDIR=".backup_dotfiles"

cmd_chk() {
    which $1 > /dev/null
    [ $? -ne 0 ] && echo "Please install \"$1\" before execute." >&2 && exit 1
    echo "command $1 found"
}

# shell check
echo "checking shell..."
ps $$|grep zsh > /dev/null
[ $? -ne 0 ] && echo "Please use zsh before execute." >&2 && exit 1

# prepare basic packages
echo "install basic packages..."
case "${OSTYPE}" in
    freebsd*|darwin*)
        echo "setup for MacOSX"
        cmd_chk brew
        brew update
        INSTALLS=("autojump" "coreutils" "colordiff" "colorsvn" "nmap" "wget")
        for t in ${INSTALLS[@]}; do
            brew list $t >/dev/null
            if [ $? -eq 1 ]; then
                brew install $t
            else
                echo "skip install: $t"
            fi
        done
        ;;
    linux*)
        if [ `lsb_release --short --id | grep 'Ubuntu'` ]; then
            echo "setup for Ubuntu"
            sudo apt-get install -y autojump colordiff curl
        fi
        ;;
    *)
        echo "who"
        ;;
esac
echo ""

echo "check needle commands..."
NEED_COMMANDS=("git" "vim")
for c in ${NEED_COMMANDS[@]}; do
    cmd_chk $c
done

# git clone dotfiles
cd ~
if [ ! -d ~/dotfiles ]; then
    git clone --recursive ${_REPOS}
else
    echo "dotfiles is already installed"
fi

# install .xxx files
echo "enable dotfiles..."
if [ ! -d ${_BACKUPDIR} ]; then
    setopt EXTENDED_GLOB
    ln -s "${ZDOTDIR:-$HOME}"/dotfiles/prezto  "${ZDOTDIR:-$HOME}"/.zprezto
    for rcfile in "${ZDOTDIR:-$HOME}"/.zprezto/runcoms/^README.md(.N); do
        ln -s "$rcfile" "${ZDOTDIR:-$HOME}/.${rcfile:t}"
    done
fi
    #mkdir -p ${_BACKUPDIR}
    #for l in `find dotfiles -mindepth 1 -maxdepth 1 ! -name '.git*' -a ! -name 'README' -a ! -name 'apply_dotfiles'`; do
    #    [ -a `basename $l` ] && mv `basename $l` ${_BACKUPDIR}/
    #    ln -s $l `basename $l`
    #done

# install vim plugin manager
curl https://raw.githubusercontent.com/Shougo/dein.vim/master/bin/installer.sh|bash -s -- .vim
ln -s "${ZDOTDIR:-$HOME}"/dotfiles/vimrc  "${ZDOTDIR:-$HOME}"/.vimrc


exit 0
